### ISSUE TITLE
R4 Revolution kernel (unencrypted) does not boot.

### ISSUE THREAD

**Issue by m4x10187** [lifehackerhansol/flashcard-bootstrap#3]
I cannot get "_DS_MENU.DAT" after decrypting the file along with copying over the other kernel files, to run alongside my flashcard. It starts displaying a bunch of graphical glitches on the top-half of the screen. Perhaps this might be a DLDI issue? I'm not 100% certain.

**Comment by lifehackerhansol** [comment]
There's no DLDI to patch in the original kernel. (Meaning there is no actual space allocated in the DLDI to patch, and the DLDI magic header doesn't exist).

I'm frankly not sure where the issue lies.
