### ISSUE TITLE
Missing files R4i 3ds gold plus www.r4ids.cn

### ISSUE THREAD

**Issue by dracula99gr** [lifehackerhansol/flashcard-bootstrap#6]
The kernel file doesn't seem to be enough to use twilight menu for booting other homebrew (using kernel), I had to download _wfwd folder files + wfwd.dat from the twilight menu zip

**Comment by lifehackerhansol** [comment]
You're not supposed to use the kernel files here to do what you are saying. The wfwd stuff from TWiLight is there for that purpose.
